#!/bin/bash
. common/libc.sh

get_current_ubuntu trusty i386 libc6
get_current_ubuntu trusty amd64 libc6
get_current_ubuntu trusty amd64 libc6-i386
#get_current_ubuntu utopic i386 libc6
#get_current_ubuntu utopic amd64 libc6
#get_current_ubuntu utopic amd64 libc6-i386
#get_current_ubuntu vivid i386 libc6
#get_current_ubuntu vivid amd64 libc6
#get_current_ubuntu vivid amd64 libc6-i386
#get_current_ubuntu wily i386 libc6
#get_current_ubuntu wily amd64 libc6
#get_current_ubuntu wily amd64 libc6-i386
get_current_ubuntu xenial i386 libc6
get_current_ubuntu xenial amd64 libc6
get_current_ubuntu xenial amd64 libc6-i386
get_current_ubuntu yakkety i386 libc6
get_current_ubuntu yakkety amd64 libc6
get_current_ubuntu yakkety amd64 libc6-i386
get_current_ubuntu zesty i386 libc6
get_current_ubuntu zesty amd64 libc6
get_current_ubuntu zesty amd64 libc6-i386

get_all_ubuntu archive-eglibc http://security.ubuntu.com/ubuntu/pool/main/e/eglibc/
get_all_ubuntu archive-glibc http://security.ubuntu.com/ubuntu/pool/main/g/glibc/

get_current_debian wheezy i386 libc6
get_current_debian wheezy amd64 libc6
get_current_debian wheezy amd64 libc6-i386
get_current_debian jessie i386 libc6
get_current_debian jessie amd64 libc6
get_current_debian jessie amd64 libc6-i386
get_current_debian stretch i386 libc6
get_current_debian stretch amd64 libc6
get_current_debian stretch amd64 libc6-i386
get_current_debian sid i386 libc6
get_current_debian sid amd64 libc6
get_current_debian sid amd64 libc6-i386
